# Generated by Django 3.0 on 2024-06-11 10:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('TiendaApp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='producto',
            name='created',
        ),
        migrations.RemoveField(
            model_name='producto',
            name='updated',
        ),
    ]
