# Generated by Django 3.0 on 2024-06-09 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ContenidoApp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='categoria',
            old_name='fecha_creacion',
            new_name='fecha_creacion_post',
        ),
        migrations.RenameField(
            model_name='post',
            old_name='fecha_creacion',
            new_name='fecha_creacion_post',
        ),
        migrations.AddField(
            model_name='post',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to='contenido'),
        ),
    ]
