# Generated by Django 3.0 on 2024-06-11 09:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ContenidoApp', '0002_auto_20240609_1750'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='categoria',
            options={'verbose_name': 'Categoria', 'verbose_name_plural': 'Categorias'},
        ),
        migrations.AlterModelOptions(
            name='post',
            options={'verbose_name': 'Post', 'verbose_name_plural': 'Posts'},
        ),
    ]
